worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        server_name portal.delnixa.ai;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name portal.delnixa.ai;

        ssl_certificate /etc/letsencrypt/live/portal.delnixa.ai/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/portal.delnixa.ai/privkey.pem;

        location / {
            proxy_pass http://delnixa-portal-web-1:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /central/login {
            proxy_pass http://delnixa-portal-api-1:8000/central/login;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/ {
            proxy_pass http://delnixa-portal-api-1:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
